apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  labels:
    app: frontend
spec:
  replicas: 3  # Number of pods you want
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend-container
          image: your-frontend-image:latest  # Replace with your actual image
          ports:
            - containerPort: 80  # Replace with your app's port
          imagePullPolicy: Always
